"""Headless WHOOP authorization (ADR-0019 §3).

The end-to-end flows need a real WHOOP login and are not tested. What IS tested
is everything that decides whether a callback is trustworthy — because the
headless path is a second door into the same house, and a second door that
forgot the lock is worse than no second door.

No network: the OAuth object is a stub whose ``exchange_code`` records the call.
"""

from __future__ import annotations

import pytest

from coach.adapters.whoop.flow import _exchange, parse_redirect, run_login_headless


class _StubOAuth:
    def __init__(self) -> None:
        self.exchanged: list[str] = []

    def authorize_url(self, *, state: str) -> str:
        return f"https://api.prod.whoop.com/oauth/oauth2/auth?state={state}"

    def exchange_code(self, code: str) -> str:
        self.exchanged.append(code)
        return f"tokens-for-{code}"


class _StubStore:
    def __init__(self) -> None:
        self.saved: list[str] = []

    def save(self, tokens: str) -> None:
        self.saved.append(tokens)


# ---- parsing what the operator pastes --------------------------------------


def test_a_full_redirect_url_is_parsed():
    params = parse_redirect("https://coach.example.com/callback?code=abc123&state=xyz")
    assert params == {"code": "abc123", "state": "xyz"}


def test_surrounding_whitespace_and_quotes_are_tolerated():
    """Copying from a terminal or a chat window picks these up. Failing on them
    sends the operator debugging their OAuth config instead of their clipboard."""
    params = parse_redirect('  "https://coach.example.com/callback?code=a&state=b"  \n')
    assert params == {"code": "a", "state": "b"}


def test_a_bare_query_string_works_too():
    assert parse_redirect("code=a&state=b") == {"code": "a", "state": "b"}


def test_a_bare_code_is_refused():
    """The state check is the only thing standing between this flow and an
    injected code. Accepting input that cannot be checked silently removes it.

    A bare code carries no parameters at all, so it is turned away with the
    same 'paste the whole URL' guidance — which is the fix in both cases.
    """
    with pytest.raises(RuntimeError, match="FULL"):
        parse_redirect("abc123")


def test_a_redirect_carrying_a_code_but_no_state_is_refused():
    """The sharper version of the same rule: parameters are present, but the one
    that proves provenance is missing. Silently proceeding here is the bug."""
    with pytest.raises(RuntimeError, match="no 'state' parameter"):
        parse_redirect("https://coach.example.com/callback?code=abc123")


def test_empty_input_says_so():
    with pytest.raises(RuntimeError, match="nothing pasted"):
        parse_redirect("   ")


def test_unparseable_input_asks_for_the_full_url():
    with pytest.raises(RuntimeError, match="FULL"):
        parse_redirect("https://coach.example.com/callback")


# ---- the shared security checks --------------------------------------------


def test_a_mismatched_state_is_refused():
    oauth, store = _StubOAuth(), _StubStore()
    with pytest.raises(RuntimeError, match="state mismatch"):
        _exchange(oauth, store, {"code": "c", "state": "wrong"}, "right")
    assert oauth.exchanged == []  # never got as far as spending the code
    assert store.saved == []


def test_whoops_own_error_is_surfaced_verbatim():
    """'No authorization code received' would send someone hunting for a network
    fault. If WHOOP said why it refused, say that instead."""
    oauth, store = _StubOAuth(), _StubStore()
    with pytest.raises(RuntimeError, match="access_denied"):
        _exchange(
            oauth,
            store,
            {"error": "access_denied", "error_description": "user declined", "state": "s"},
            "s",
        )


def test_a_missing_code_is_refused():
    oauth, store = _StubOAuth(), _StubStore()
    with pytest.raises(RuntimeError, match="No authorization code"):
        _exchange(oauth, store, {"state": "s"}, "s")


def test_a_good_callback_exchanges_and_stores():
    oauth, store = _StubOAuth(), _StubStore()
    tokens = _exchange(oauth, store, {"code": "c0de", "state": "s"}, "s")
    assert oauth.exchanged == ["c0de"]
    assert store.saved == [tokens]


# ---- the headless flow end to end (no browser, no socket) ------------------


def test_headless_login_round_trips(monkeypatch):
    oauth, store = _StubOAuth(), _StubStore()
    printed: list[str] = []
    # Capture the state the flow generated by reading it back off the URL it
    # printed — exactly what a real operator does with their browser.
    urls: list[str] = []

    def _echo(msg: str) -> None:
        printed.append(msg)
        if "oauth2/auth?state=" in msg:
            urls.append(msg.strip())

    def _prompt(_label: str) -> str:
        state = urls[0].split("state=")[1]
        return f"https://coach.example.com/callback?code=real-code&state={state}"

    tokens = run_login_headless(oauth, store, prompt=_prompt, echo=_echo)

    assert oauth.exchanged == ["real-code"]
    assert store.saved == [tokens]
    # The operator is warned that the callback page failing to load is normal —
    # without it, the flow looks broken at exactly the moment it is working.
    assert any("may fail to load" in m for m in printed)


def test_headless_login_refuses_a_replayed_state(monkeypatch):
    """A callback from some *other* authorization must not be accepted."""
    oauth, store = _StubOAuth(), _StubStore()

    def _prompt(_label: str) -> str:
        return "https://coach.example.com/callback?code=c&state=from-a-different-login"

    with pytest.raises(RuntimeError, match="state mismatch"):
        run_login_headless(oauth, store, prompt=_prompt, echo=lambda _m: None)
    assert store.saved == []
